rule qualimap:
    input:
        # BAM aligned, splicing-aware, to reference genome
        bam="mapped/a.bam",
    output:
        directory("qc/a"),
    params:
        html_report=True  # necessary for full MultiQC compatibility  https://multiqc.info/docs/#qualimap
                          # for PDF reports set to False and add param extra="-outformat PDF"
    log:
        "logs/qualimap/bamqc/a.log",
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    wrapper:
        "master/bio/qualimap/bamqc"
