rule contig_information:
    input:
        "genome.fasta",
    output:
        "genome.contig_information.tsv",
    log:
        "logs/genome_contiginformation.log",
    wrapper:
        "https://raw.githubusercontent.com/mobilegenome/snakemake-wrappers/genome_contiginfo/bio/reference/genome-contiginformation/"
