rule contig_information:
    input:
        "genome.fasta"
    output:
        "genome.contig_information.tsv"
    wrapper:
        "file://home/fritjof/code/snakemake-wrappers/bio/reference/genome-contiginformation"